apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-gkbv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-wahx-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-gkbv@sha256:b0a8a83a5a7849dba4ca46afc0485b08de6a649220aa846624cefe832d3af669
        name: my-nodejs
        resources: {}
status: {}
